#!/usr/bin/env bash

# This script propagates the extracted C and assembly code for miTLS and 
# HACL* out into standalone directories.

# set -x

print_usage ()
{
  cat <<HELP
Usage:  MakeSourceDrop destination_path
  make-source-drop ~/drops/drop12

The directory path will be created if it doesn't already exist.
HELP
}

if [[ $1 == "" ]]; then
  print_usage
  exit 0
fi

# set current directory to the directory of this script
cd "${BASH_SOURCE%/*}" || exit

MITLS_EXTRACT=mitls-fstar/src/tls/dist
KREMLIB=kremlin/kremlib
HACL_HOME=hacl-star
HACL_CODE=hacl-star/code

# Headers #####################################################################

mkdir -p $1/include
cp mitls-fstar/libs/ffi/mitlsffi.h $1/include
cp hacl-star/providers/quic_provider/quic_provider.h $1/include
cp hacl-star/dist/evercrypt-external-headers/EverCrypt.h $1/include
cp kremlin/include/kremlib.h $1/include
cp mitls-fstar/src/tls/cstubs/RegionAllocator.h $1/include
cp -R kremlin/include/* $1/include
cp -R kremlin/kremlib/dist/generic/{FStar_UInt128.h,fstar_uint128_msvc.h,LowStar_Endianness.h,FStar_UInt_8_16_32_64.h} $1/include

# libkremlib ##################################################################
mkdir -p $1/kremlib
cp -R kremlin/kremlib/dist/generic/*.{c,h} $1/kremlib/
cp mitls-fstar/src/tls/cstubs/RegionAllocator.c $1/kremlib

# libevercrypt ################################################################
mkdir -p $1/evercrypt
mkdir -p $1/evercrypt/amd64
mkdir -p $1/evercrypt/i386

cp hacl-star/dist/compact-msvc/*x86_64*.asm $1/evercrypt/amd64
cp hacl-star/dist/compact-msvc/*i686*.asm $1/evercrypt/i386
cp hacl-star/dist/compact-msvc/*.{c,h} $1/evercrypt

# libmitls ####################################################################
mkdir -p $1/mitls
#Don't remove dllmain.c
#rm -f $1/mitls/*.c
find $1/mitls -maxdepth 1 -type f -and -name '*.c' -and -not -name dllmain.c | xargs rm -f
rm -f $1/mitls/*.h
cp $MITLS_EXTRACT/compact-msvc/*.{c,h} $1/mitls
rm $1/mitls/RegionAllocator.*

# libquiccrypto ###############################################################
mkdir -p $1/quiccrypto
find $1/quiccrypto -maxdepth 1 -type f -and -name '*.c' -and -not -name dllmain.c | xargs rm -f
find $1/quiccrypto -maxdepth 1 -type f -and -name '*.h' -and -not -name CommonInclude.h | xargs rm -f

cp hacl-star/providers/quic_provider/quic_provider.c $1/quiccrypto
cp hacl-star/providers/quic_provider/test.c $1/quiccrypto

# binaries
mkdir -p $1/bin
rm -f $1/bin/*.dll
cp mitls-fstar/src/tls/dist/compact-msvc/libmitls.dll $1/bin
cp MLCrypto/openssl/libcrypto-1_1-x64.dll $1/bin
cp hacl-star/providers/quic_provider/libquiccrypto.dll $1/bin
cp hacl-star/dist/compact/libevercrypt.dll $1/bin

# hashes
cp hashes.sh $1/
