#!/usr/bin/env bash

# This script propagates the extracted C and assembly code for miTLS and 
# HACL* out into standalone directories.

# set -x

print_usage ()
{
  cat <<HELP
Usage:  MakeSourceDrop destination_path
  make-source-drop ~/drops/drop12

The directory path will be created if it doesn't already exist.
HELP
}

if [[ $1 == "" ]]; then
  print_usage
  exit 0
fi

# set current directory to the directory of this script
cd "${BASH_SOURCE%/*}" || exit

MITLS_EXTRACT=mitls-fstar/src/tls/extract
KREMLIB=kremlin/kremlib
HACL=hacl-star/secure_api
HACL_HOME=hacl-star
HACL_CODE=hacl-star/code

# Headers #####################################################################

mkdir -p $1/include
cp mitls-fstar/libs/ffi/mitlsffi.h $1/include
cp hacl-star/providers/quic_provider/quic_provider.h $1/include
cp hacl-star/providers/include/EverCrypt.h $1/include
cp kremlin/include/kremlib.h $1/include
cp mitls-fstar/src/tls/extract/cstubs/RegionAllocator.h $1/include
cp -R kremlin/include/* $1/include

# libkremlib ##################################################################
cp kremlin/kremlib/extracted/*.h $1/kremlib
for w in 8 16 32 64; do
  cp kremlin/kremlib/extracted/FStar_UInt$w.c $1/kremlib/fstar_uint${w}_generated.c
done
cp kremlin/kremlib/c/*.c $1/kremlib
cp mitls-fstar/src/tls/extract/cstubs/RegionAllocator.c $1/kremlib

# libevercrypt ################################################################
cp hacl-star/providers/generated/*.{c,h} $1/evercrypt
cp hacl-star/providers/evercrypt/c/*.c $1/evercrypt

# these are the individual implementations from Hacl; they override
# corresponding files from the provider that only contain "extern" definitions;
# technically each one of these algorithms should be compiled seperately into
# its own .obj then linked together at the end
touch $1/evercrypt/WasmSupport.h
#cp $HACL_HOME/snapshots/common/vec128.h $1/evercrypt
cp $HACL_CODE/salsa-family/chacha-c/Hacl_Chacha20.{c,h} $1/evercrypt
cp $HACL_CODE/salsa-family/salsa-c/Hacl_Salsa20.{c,h} $1/evercrypt
cp $HACL_CODE/hash/sha2-c/Hacl_SHA2_256.{c,h} $1/evercrypt
cp $HACL_CODE/hash/sha2-c/Hacl_SHA2_384.{c,h} $1/evercrypt
cp $HACL_CODE/hash/sha2-c/Hacl_SHA2_512.{c,h} $1/evercrypt
cp $HACL_CODE/curve25519/x25519-c/Hacl_Curve25519.{c,h} $1/evercrypt
cp $HACL_CODE/ed25519/ed25519-c/Hacl_Ed25519.{c,h} $1/evercrypt
cp $HACL_CODE/poly1305/poly-c/Hacl_Poly1305_64.{c,h} $1/evercrypt
cp $HACL_CODE/hmac/hmac-sha256-c/Hacl_HMAC_SHA2_256.{c,h} $1/evercrypt
cp $HACL_CODE/poly1305/poly-c/AEAD_Poly1305_64.{c,h} $1/evercrypt
#cp $HACL_CODE/salsa-family/chacha-vec128-c/Hacl_Chacha20_Vec128.{c,h} $1/evercrypt
cp $HACL_CODE/api/aead-c/Hacl_*.{c,h} $1/evercrypt
cp $HACL_CODE/api/policies-c/Hacl_Policies.{c,h} $1/evercrypt

# vale thingies
cp $HACL/vale/asm/{aes.h,vale_aes_glue.c} $1/evercrypt
cp $HACL/vale/asm/{DafnyLib.h,sha256_main_i.h,sha256_main_i.c,Vale_Hash_SHA2_256.c} $1/evercrypt

mkdir -p $1/evercrypt
mkdir -p $1/evercrypt/amd64
mkdir -p $1/evercrypt/i386
cp $HACL/vale/asm/*x86_64*.asm $1/evercrypt/amd64
cp $HACL/vale/asm/*i686*.asm $1/evercrypt/i386

# libmitls ####################################################################
mkdir -p $1/mitls
#Don't remove dllmain.c
#rm -f $1/mitls/*.c
find $1/mitls -maxdepth 1 -type f -and -name '*.c' -and -not -name dllmain.c | xargs rm -f
rm -f $1/mitls/*.h
cp $MITLS_EXTRACT/Kremlin-Library/*.{c,h} $1/mitls
cp $MITLS_EXTRACT/Kremlin-Library/include/*.h $1/mitls
cp $MITLS_EXTRACT/Kremlin-Library/stub/*.{c,h} $1/mitls
rm $1/mitls/RegionAllocator.*

# libquiccrypto ###############################################################
mkdir -p $1/quiccrypto
find $1/quiccrypto -maxdepth 1 -type f -and -name '*.c' -and -not -name dllmain.c | xargs rm -f
find $1/quiccrypto -maxdepth 1 -type f -and -name '*.h' -and -not -name CommonInclude.h | xargs rm -f

cp hacl-star/providers/quic_provider/quic_provider.c $1/quiccrypto
cp hacl-star/providers/quic_provider/test.c $1/quiccrypto

# binaries
mkdir -p $1/bin
rm -f $1/bin/*.dll
cp mitls-fstar/src/tls/extract/Kremlin-Library/libmitls.dll $1/bin
cp MLCrypto/openssl/libcrypto-1_1-x64.dll $1/bin
cp hacl-star/providers/quic_provider/libquiccrypto.dll $1/bin
cp hacl-star/providers/out/libevercrypt.dll $1/bin

# hashes
cp hashes.sh $1/

