#!/usr/bin/env bash

set -e
set -o pipefail

# This script contains a series of commands that, when run within a fresh Docker
# Ubuntu container, setup the environment and build project everest, all the way
# to the final (known) working test.

# Known required packages
yes | apt-get update
yes | apt-get install wget build-essential opam libsqlite3-dev libgmp-dev libssl-dev m4 automake git fsharp

# Z3
wget https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip
unzip z3*
export PATH=$(pwd)/z3-4.5.0-x64-ubuntu-14.04/bin:$PATH

# Worksaround a bug in OPAM https://github.com/ocaml/opam/issues/2767
export OPAMYES=true
git clone https://github.com/project-everest/everest

# Build everything
yes | everest/everest check pull make

# The "final" test
everest/mitls-fstar/src/tls/mitls.exe
echo "EVEREST-SUCCESS"
